(()=>{"use strict";
const id=new URLSearchParams(location.search).get("object")||"default",p="atemir_entity_"+id+"_",PAGE=50;let filter="all",search="",page=1;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),num=v=>parseFloat(String(v??0).replace(",","."))||0,norm=v=>String(v||"").trim().toUpperCase().replace(/\s+/g,"");
function db(k){try{return window.atemirDesktop?.dbGetSync?.(k)}catch{return null}} function set(k,v){return window.atemirDesktop?.dbSet?.(k,v)}
function load(){const ti=db(p+"taskIndex")||[],tasks=ti.sort((a,b)=>(a.sort??0)-(b.sort??0)).map(x=>db(p+"task_"+x.id)).filter(Boolean);tasks.forEach(t=>t.bom=db(p+"bom_"+t.id)||[]);const ri=db(p+"reportIndex")||[],reports=ri.map(x=>db(p+"report_"+x.id)).filter(Boolean),ii=db(p+"invoiceIndex")||[],invoices=ii.map(x=>db(p+"invoice_"+x.id)).filter(Boolean);return{tasks,reports,invoices}}
function style(){if(document.getElementById("bomNativeCss"))return;const s=document.createElement("style");s.id="bomNativeCss";s.textContent=`
body.bomNativeActive #view{font-size:12px!important;background:#f5f8fa!important;padding:14px!important}
body.bomNativeActive #view>div:not(#bomNative),body.bomNativeActive #view>section:not(#bomNative){box-sizing:border-box}
body.bomNativeActive #view .card{background:#fff!important;border:1px solid #dce5eb!important;border-radius:11px!important;padding:16px 18px!important;margin:0 0 12px!important;box-shadow:0 1px 3px rgba(24,55,75,.035)!important}
body.bomNativeActive #view .rowhead{margin-bottom:12px!important}body.bomNativeActive #view .rowhead b{font-size:14px!important;color:#17364d!important}
body.bomNativeActive #view .grid{gap:14px!important}body.bomNativeActive #view label{color:#667d8c!important;font-size:10px!important}
body.bomNativeActive #view select{height:40px!important;border:1px solid #d5e0e7!important;border-radius:8px!important;background:#fff!important;padding:0 11px!important;color:#28485c!important;font-size:11px!important;box-sizing:border-box!important}
body.bomNativeActive #bomUpload517{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:40px!important;padding:0 18px!important;border:0!important;border-radius:8px!important;background:#1695cf!important;color:#fff!important;font-size:11px!important;font-weight:700!important;cursor:pointer!important;opacity:1!important}
body.bomNativeActive #bomUpload517:hover{background:#117fb2!important}body.bomNativeActive #bomProjectFilter714{height:40px!important;min-width:360px!important;max-width:100%!important}
body.bomNativeActive #view>.stat,body.bomNativeActive #view>.toolbar,body.bomNativeActive #view>.bomLock241,body.bomNativeActive #bomRows{display:none!important}
.bomNative{margin-top:2px}.bomNative .bnStats{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:10px;margin:14px 0}.bomNative .bnStat{background:#fff;border:1px solid #dce5eb;border-radius:10px;padding:13px 14px}.bomNative .bnStat span{display:block;color:#718392;font-size:10px}.bomNative .bnStat b{display:block;margin-top:3px;color:#17364d;font-size:18px}.bomNative .bnStat.good b{color:#23885a}
.bomNative .bnTools{display:flex;gap:9px;align-items:center;background:#fff;border:1px solid #dce5eb;border-radius:10px;padding:10px;margin-bottom:12px}.bomNative .bnTools input{flex:1;min-width:160px;height:38px;border:1px solid #d5e0e7;border-radius:7px;padding:0 12px;font-size:11px;outline:none}.bomNative .bnTools input:focus{border-color:#1695cf;box-shadow:0 0 0 3px rgba(22,149,207,.10)}
.bomNative button,.bnModal button{height:36px;border:1px solid #ccd9e2;border-radius:7px;background:#fff;color:#24465c;padding:0 13px;font-size:10px;font-weight:700;cursor:pointer}.bomNative button:hover,.bnModal button:hover{background:#f2f7fa}.bomNative button.on{background:#1695cf;border-color:#1695cf;color:#fff}.bomNative .bnAdd{margin-left:auto;background:#1695cf!important;border-color:#1695cf!important;color:#fff!important;white-space:nowrap}.bomNative .bnAdd:hover{background:#117fb2!important}
.bomNative .bnInfo{padding:10px 12px;border:1px solid #d7e7f0;border-radius:8px;background:#f5fbfe;color:#526d7e;font-size:10px;margin-bottom:12px}.bomNative .bnTable{background:#fff;border:1px solid #dce5eb;border-radius:10px;overflow:hidden}.bomNative .bnHead,.bomNative .bnRow{display:grid;grid-template-columns:110px minmax(210px,1.5fr) 70px 85px 85px 105px 55px minmax(120px,1fr) 72px;gap:9px;align-items:center;padding:0 13px}.bomNative .bnHead{height:38px;background:#f3f6f8;color:#718392;font-size:9.5px}.bomNative .bnRow{min-height:47px;border-top:1px solid #e7edf1;color:#496273;font-size:10px}.bomNative .bnRow:hover{background:#f8fbfd}.bomNative .bnMark{font-weight:800;color:#173a51}.bomNative .bnStatus{display:inline-flex;justify-content:center;padding:4px 7px;border-radius:5px;background:#eef2f5;color:#718493;font-size:8px}.bomNative .bnStatus.done{background:#def5e9;color:#23885a}.bomNative .bnStatus.work{background:#e2f0fc;color:#247db9}.bomNative .bnBar{height:7px;background:#e8edf1;border-radius:8px;overflow:hidden}.bomNative .bnBar i{display:block;height:100%;background:#2994d2}.bomNative .bnBar.done i{background:#35b678}.bomNative .bnActions{display:flex;gap:4px}.bomNative .bnActions button{width:30px;height:30px;padding:0}.bomNative .bnActions .del{color:#b42318}.bomNative .bnPager{display:flex;justify-content:center;gap:6px;margin:15px}.bomNative .bnPager button.on{background:#0b78b4;color:#fff;border-color:#0b78b4}.bomNative .bnPager button:disabled{opacity:.45;cursor:default}.bomNative .bnEmpty{padding:30px;text-align:center;color:#80919e}
.bnModal{position:fixed;inset:0;z-index:9999;background:rgba(16,42,59,.38);display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box}.bnModal>div{width:560px;max-width:100%;background:#fff;border-radius:14px;padding:24px;box-shadow:0 22px 55px rgba(16,42,59,.25);box-sizing:border-box}.bnModal h3{margin:0 0 18px;color:#17364d;font-size:20px}.bnModal label{display:block;font-size:10px;color:#657b8a;margin:11px 0 5px}.bnModal input{width:100%;height:40px;border:1px solid #d5e0e7;border-radius:8px;padding:0 11px;box-sizing:border-box;font-size:12px;outline:none}.bnModal input:focus{border-color:#1695cf;box-shadow:0 0 0 3px rgba(22,149,207,.10)}.bnModal .acts{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.bnModal .save{background:#1695cf!important;color:#fff!important;border-color:#1695cf!important}.bnModal .save:hover{background:#117fb2!important}.bnModal .error{margin-top:10px;color:#b42318;font-size:10px;min-height:14px}
@media(max-width:1200px){.bomNative .bnStats{grid-template-columns:repeat(4,1fr)}.bomNative .bnTools{flex-wrap:wrap}.bomNative .bnTools input{flex-basis:100%}}
`;document.head.appendChild(s)}
function currentKey(){return document.querySelector("#bomProjectFilter714")?.value||""}
function calc(){const D=load();let key=currentKey(),tasks=D.tasks.filter(t=>(t.type||"")+"|||"+(t.code||"")===key);if(!tasks.length&&D.tasks.length){const t=D.tasks.find(x=>(x.bom||[]).length);if(t){key=(t.type||"")+"|||"+(t.code||"");tasks=[t]}}const work={},inv={};D.reports.forEach(day=>(day.items||[]).forEach(x=>{if(((x.type||"")+"|||"+(x.code||""))!==key)return;const k=norm(x.mark);work[k]=(work[k]||0)+num(x.qty)}));D.invoices.forEach(a=>(a.items||[]).forEach(x=>{if(((x.type||"")+"|||"+(x.code||""))!==key)return;const k=norm(x.mark);inv[k]=(inv[k]||0)+num(x.qty)}));const rows=[];tasks.forEach(t=>(t.bom||[]).forEach((r,idx)=>{const q=num(r.qty||r.count),done=Math.min(q,work[norm(r.mark)]||0),got=inv[norm(r.mark)]||0,pct=q?Math.min(100,Math.round(done/q*100)):0,state=pct>=100?"done":pct>0?"work":"left";rows.push({t,r,idx,q,done,got,pct,state})}));return{D,key,tasks,rows}}
function render(){const old=document.querySelector("#bomRows");if(!old)return;style();document.body.classList.add("bomNativeActive");let anchor=document.querySelector("#bomNative");if(!anchor){anchor=document.createElement("div");anchor.id="bomNative";anchor.className="bomNative";old.parentNode.insertBefore(anchor,old)}const C=calc(),rows=C.rows,total=rows.reduce((s,x)=>s+x.q,0),mounted=rows.reduce((s,x)=>s+x.done,0),donePos=rows.filter(x=>x.state==="done").length,workPos=rows.filter(x=>x.state==="work").length,notPos=rows.filter(x=>x.state==="left").length,pct=total?Math.round(mounted/total*100):0;const f=rows.filter(x=>(!search||(String(x.r.mark||"")+" "+String(x.r.name||"")).toLowerCase().includes(search))&&(filter==="all"||(filter==="done"&&x.state==="done")||(filter==="left"&&x.state!=="done"))),pages=Math.max(1,Math.ceil(f.length/PAGE));page=Math.min(page,pages);const shown=f.slice((page-1)*PAGE,page*PAGE);
anchor.innerHTML=`<div class="bnStats"><div class="bnStat"><span>Позиций марок</span><b>${rows.length}</b></div><div class="bnStat"><span>Полностью смонтировано</span><b>${donePos}</b></div><div class="bnStat"><span>В работе</span><b>${workPos}</b></div><div class="bnStat"><span>Не начато</span><b>${notPos}</b></div><div class="bnStat"><span>По проекту, шт.</span><b>${total}</b></div><div class="bnStat"><span>Смонтировано, шт.</span><b>${mounted}</b></div><div class="bnStat"><span>Осталось, шт.</span><b>${Math.max(0,total-mounted)}</b></div><div class="bnStat good"><span>Готовность</span><b>${pct}%</b></div></div><div class="bnTools"><input id="bnSearch" value="${esc(search)}" placeholder="Поиск по марке или наименованию…"><button data-bnf="all" class="${filter==="all"?'on':''}">Все</button><button data-bnf="done" class="${filter==="done"?'on':''}">Смонтировано</button><button data-bnf="left" class="${filter==="left"?'on':''}">Осталось</button><button class="bnAdd" id="bnAdd">+ Добавить марку</button></div><div class="bnInfo"><b>ⓘ Защита ведомости.</b> Используемую ведомость нельзя заменять целиком, но отдельные марки можно добавлять, редактировать и удалять.</div><div class="bnTable"><div class="bnHead"><span>Марка</span><span>Наименование</span><span>Кол-во</span><span>Поступило</span><span>Статус</span><span>Факт монтажа</span><span>%</span><span>Прогресс</span><span></span></div>${shown.length?shown.map(x=>`<div class="bnRow"><span class="bnMark">${esc(x.r.mark||"—")}</span><span>${esc(x.r.name||"")}</span><span>${x.q}</span><span>${x.got}</span><span><i class="bnStatus ${x.state}">${x.state==="done"?'Смонтировано':x.state==="work"?'В работе':'Не начато'}</i></span><span>${x.done} / ${x.q}</span><b>${x.pct}%</b><span class="bnBar ${x.state}"><i style="width:${x.pct}%"></i></span><span class="bnActions"><button data-bne="${esc(x.t.id)}:${x.idx}" title="Редактировать">✎</button><button class="del" data-bnd="${esc(x.t.id)}:${x.idx}" title="Удалить">×</button></span></div>`).join(""):'<div class="bnEmpty">Марки не найдены</div>'}</div>${pages>1?`<div class="bnPager"><button data-bnp="${page-1}" ${page===1?'disabled':''}>← Назад</button>${Array.from({length:pages},(_,i)=>i+1).map(n=>`<button data-bnp="${n}" class="${n===page?'on':''}">${n}</button>`).join("")}<button data-bnp="${page+1}" ${page===pages?'disabled':''}>Вперёд →</button></div>`:''}`;
const inp=anchor.querySelector("#bnSearch");inp.oninput=e=>{search=e.target.value.toLowerCase().trim();page=1;render();const n=document.querySelector("#bnSearch");n?.focus();if(n)n.setSelectionRange(n.value.length,n.value.length)};anchor.querySelectorAll("[data-bnf]").forEach(b=>b.onclick=()=>{filter=b.dataset.bnf;page=1;render()});anchor.querySelectorAll("[data-bnp]").forEach(b=>b.onclick=()=>{if(!b.disabled){page=+b.dataset.bnp;render()}});anchor.querySelectorAll("[data-bne]").forEach(b=>b.onclick=()=>edit(b.dataset.bne));anchor.querySelectorAll("[data-bnd]").forEach(b=>b.onclick=()=>del(b.dataset.bnd));anchor.querySelector("#bnAdd").onclick=add}
function modal(title,data,onSave){const m=document.createElement("div");m.className="bnModal";m.innerHTML=`<div><h3>${title}</h3><label>Марка</label><input id="bem" value="${esc(data.mark||"")}"><label>Наименование</label><input id="ben" value="${esc(data.name||"")}"><label>Количество</label><input id="beq" type="number" min="0" step="any" value="${esc(data.qty??0)}"><label>Масса единицы, кг</label><input id="bew" type="number" min="0" step="any" value="${esc(data.weight??0)}"><label>Общая масса, кг</label><input id="bet" type="number" min="0" step="any" value="${esc(data.totalWeight??0)}"><div class="error" id="beerr"></div><div class="acts"><button id="bec">Отмена</button><button class="save" id="bes">Сохранить</button></div></div>`;document.body.appendChild(m);m.querySelector("#bec").onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector("#bes").onclick=async()=>{const v={mark:m.querySelector("#bem").value.trim(),name:m.querySelector("#ben").value.trim(),qty:num(m.querySelector("#beq").value),weight:num(m.querySelector("#bew").value),totalWeight:num(m.querySelector("#bet").value)};if(!v.mark){m.querySelector("#beerr").textContent="Укажите марку.";return}if(v.qty<=0){m.querySelector("#beerr").textContent="Количество должно быть больше нуля.";return}const ok=await onSave(v,m);if(ok!==false){m.remove();render()}};setTimeout(()=>m.querySelector("#bem")?.focus(),0)}
function edit(ref){const [tid,ix]=ref.split(":"),C=calc(),t=C.D.tasks.find(x=>String(x.id)===tid),r=t?.bom?.[+ix];if(!r)return;modal("Редактировать марку",{mark:r.mark,name:r.name,qty:r.qty||r.count||0,weight:r.weight||r.unitWeight||0,totalWeight:r.totalWeight||0},async v=>{Object.assign(r,v);await set(p+"bom_"+tid,t.bom);return true})}
function add(){const C=calc();if(!C.tasks.length){alert("Сначала выберите ведомость / шифр проекта, в который нужно добавить марку.");return}const t=C.tasks[0];modal("Добавить марку",{qty:1,weight:0,totalWeight:0},async(v,m)=>{const exists=C.rows.some(x=>norm(x.r.mark)===norm(v.mark));if(exists){m.querySelector("#beerr").textContent="Марка с таким обозначением уже есть в этой ведомости.";return false}t.bom.push(v);await set(p+"bom_"+t.id,t.bom);page=Math.max(1,Math.ceil((C.rows.length+1)/PAGE));return true})}
async function del(ref){const [tid,ix]=ref.split(":"),C=calc(),t=C.D.tasks.find(x=>String(x.id)===tid),r=t?.bom?.[+ix];if(!r)return;if(!confirm(`Удалить марку «${r.mark||"без марки"}» из ведомости?\nЗаписи в отчётах и накладных удалены не будут.`))return;t.bom.splice(+ix,1);await set(p+"bom_"+tid,t.bom);render()}
let lastOld=false;const mo=new MutationObserver(()=>{const old=document.querySelector("#bomRows");if(old&&!document.querySelector("#bomNative")){render();lastOld=true}else if(!old&&lastOld){document.querySelector("#bomNative")?.remove();document.body.classList.remove("bomNativeActive");lastOld=false}});mo.observe(document.getElementById("view")||document.body,{childList:true,subtree:true});setTimeout(render,100);
})();