(()=>{"use strict";
const oid=new URLSearchParams(location.search).get('object')||'default',P=`atemir_entity_${oid}_`;
const db=k=>{try{return window.atemirDesktop?.dbGetSync?.(k)}catch{return null}};
function unit(){const k=document.getElementById('bomProjectFilter714')?.value||'';if(!k)return'';for(const x of(db(P+'taskIndex')||[])){const t=db(P+'task_'+x.id);if(t&&`${t.type||''}|||${t.code||''}`===k)return String(t.unit||t.measure||t.measureUnit||'').trim()}return''}
function css(){if(document.getElementById('bomUi257Css'))return;const s=document.createElement('style');s.id='bomUi257Css';s.textContent=`
body.bn252 #view>.card:first-child .grid{grid-template-columns:minmax(260px,1fr) minmax(260px,1fr) 264px!important;gap:14px!important;align-items:end!important}
body.bn252 #view>.card:first-child .grid>div:last-child{display:flex!important;flex-direction:column!important;align-items:stretch!important;justify-content:flex-end!important}
body.bn252 #bomUpload517{width:264px!important;height:42px!important;min-height:42px!important;margin:0!important;align-items:center!important;justify-content:center!important;background:#1695cf!important;border:1px solid #1695cf!important;border-radius:8px!important;color:#fff!important;-webkit-text-fill-color:#fff!important;font-size:11px!important;font-weight:800!important;line-height:1!important;opacity:1!important;cursor:pointer!important}
.bomHelp257{position:relative;display:flex;justify-content:center;margin-top:7px}.bomHelpBtn257{border:0;background:transparent;color:#647d8e;font-size:10px;cursor:pointer;padding:3px 7px}.bomHelpBtn257 b{display:inline-grid;place-items:center;width:19px;height:19px;margin-right:5px;border-radius:50%;background:#edf8fc;color:#1695cf;font-size:11px}.bomHelpPop257{display:none;position:absolute;right:0;top:28px;z-index:2000;width:470px;padding:14px;background:#fff;border:1px solid #d8e3e9;border-radius:9px;box-shadow:0 12px 30px rgba(24,55,75,.18);color:#526b7b;font-size:10px;line-height:1.5}.bomHelpPop257.open{display:block}.bomHelpPop257 strong{display:block;color:#17364d;font-size:11px;margin-bottom:6px}.bomHelpTable257{display:grid;grid-template-columns:62px 1fr 62px 78px 88px;margin:9px 0;border:1px solid #dfe7ec;border-radius:6px;overflow:hidden}.bomHelpTable257 span{padding:6px;border-right:1px solid #e5ebef;border-bottom:1px solid #e5ebef}.bomHelpTable257 span:nth-child(-n+5){font-weight:700;color:#29485b;background:#f5f8fa}.bomHelpDl257{border:0;background:transparent;color:#1683bb;font-weight:700;cursor:pointer;padding:2px 0}.bnModal252 .bnUnitWrap257{margin-top:0}.bnModal252 .bnUnit257{width:100%;height:40px;border:1px solid #d5e0e7;border-radius:8px;padding:0 11px;box-sizing:border-box;background:#f4f7f9;color:#29485b;font-size:12px;font-weight:700}.bnHead,.bnRow{grid-template-columns:90px minmax(145px,1.2fr) 52px 58px 72px 76px 70px 82px 86px 42px minmax(90px,.72fr) 68px!important}.bnUnitCell257{font-weight:700;color:#526d7e}
@media(max-width:1200px){body.bn252 #view>.card:first-child .grid{grid-template-columns:1fr 1fr!important}body.bn252 #view>.card:first-child .grid>div:last-child{grid-column:1/-1!important;width:264px!important}}
`;document.head.appendChild(s)}
function modalUnit(){const m=document.querySelector('.bnModal252');if(!m||m.querySelector('.bnUnitWrap257')||m.querySelector('.bnUnitWrap255'))return;const labels=[...m.querySelectorAll('label')],q=labels.find(x=>x.textContent.trim()==='Количество');if(!q)return;const inp=q.nextElementSibling;if(!inp)return;const w=document.createElement('div');w.className='bnUnitWrap257';w.innerHTML='<label>Единица измерения</label><input class="bnUnit257" readonly>';inp.insertAdjacentElement('afterend',w);w.querySelector('input').value=unit()||'—'}
function tableUnit(){const r=document.getElementById('bomNative');if(!r)return;const u=unit()||'—',h=r.querySelector('.bnHead');if(h&&!h.querySelector('.bnUnitHead255')&&!h.querySelector('.bnUnitHead257')){const e=document.createElement('span');e.className='bnUnitHead257';e.textContent='Ед. изм.';h.insertBefore(e,h.children[3]||null)}r.querySelectorAll('.bnRow').forEach(x=>{if(x.querySelector('.bnUnit255,.bnUnitCell257'))return;const e=document.createElement('span');e.className='bnUnitCell257';e.textContent=u;x.insertBefore(e,x.children[3]||null)})}
function help(){const b=document.getElementById('bomUpload517');if(!b||document.querySelector('.bomHelp257'))return;const host=b.parentElement;if(!host)return;const h=document.createElement('div');h.className='bomHelp257';h.innerHTML=`<button type="button" class="bomHelpBtn257"><b>?</b>Как подготовить Excel</button><div class="bomHelpPop257"><strong>Формат таблицы для загрузки</strong>Первая строка — названия колонок. Каждая марка — отдельная строка. Не объединяйте ячейки и не добавляйте промежуточные заголовки.<div class="bomHelpTable257"><span>Марка</span><span>Наименование</span><span>Количество</span><span>Объём 1 ед.</span><span>Общий объём</span><span>К1</span><span>Ригель фахверка</span><span>2</span><span>38</span><span>76</span></div><button type="button" class="bomHelpDl257">↓ Скачать пример CSV</button></div>`;host.appendChild(h);const p=h.querySelector('.bomHelpPop257');h.querySelector('.bomHelpBtn257').onclick=e=>{e.stopPropagation();p.classList.toggle('open')};h.querySelector('.bomHelpDl257').onclick=()=>{const txt='Марка;Наименование;Количество;Объём 1 ед.;Общий объём\r\nК1;Ригель фахверка;2;38;76\r\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+txt],{type:'text/csv;charset=utf-8'}));a.download='Пример_ведомости_марок.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.addEventListener('click',e=>{if(!h.contains(e.target))p.classList.remove('open')})}
function apply(){css();help();modalUnit();tableUnit()}
let q=false;function queue(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;apply()})}
function boot(){apply();new MutationObserver(queue).observe(document.getElementById('view')||document.body,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target?.id==='bomProjectFilter714')queue()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();